name: Build Docker Image, Push to GHCR

on:
  push:
    branches:
    - main
  workflow_dispatch: # Allows manual trigger

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/sunu/jupyterhub-gitpuller-init:latest
          ghcr.io/sunu/jupyterhub-gitpuller-init:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max