name: Build Docker Image, Push to GHCR

on:
  push:
    branches:
    - main
  workflow_dispatch: # Allows manual trigger

permissions:
  packages: write

env:
  REGISTRY_BASE_URL: public.ecr.aws
  ECR_NAMESPACE: i8x6m1u9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to AWS ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY_BASE_URL }}/${{ env.ECR_NAMESPACE }}/jupyterhub-gitpuller-init:latest
          ${{ env.REGISTRY_BASE_URL }}/${{ env.ECR_NAMESPACE }}/jupyterhub-gitpuller-init:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
